apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.sfapm_celery.sftrace.serviceAccountName }}
  labels:
    {{- include "sfapm.labels" . | nindent 4 }}
{{- with .Values.global.serviceAccount.imagePullSecrets }}
imagePullSecrets:
  {{- range .Values.global.serviceAccount.imagePullSecrets }}
  - {{ . }}
  {{- end }}
{{- end }}