apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.global.sfapm_celery.sftrace.clusterRoleBindingName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.global.sfapm_celery.sftrace.serviceAccountName }}
roleRef:
  kind: Role
  name: {{ .Values.global.sfapm_celery.sftrace.clusterRoleName }}
  apiGroup: rbac.authorization.k8s.io