apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sf-scheduler.fullname" . }}-configmapv2
data:
  sf-scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
    - schedulerName: sf-scheduler
    plugins:
      score:
        disabled:
        - name: '*'
        enabled:
        - name: NodeAffinity
        - name: TaintToleration
        - name: NodeResourcesBalancedAllocation
        - name: InterPodAffinity
        - name: PodTopologySpread
    leaderElection:
      leaderElect: false