enableDebug: false
archiverEnabled: true
nameOverride: sfapm-python3
fullnameOverride: ""

image:
  pullPolicy: IfNotPresent
  repository: snappyflowml/sftrace-server
  tag: '0-1-23'

sftrace-server-prometheus-exporter:
  image:
    repository: snappyflowml/sftrace-server-prometheus-exporter
    tag: 'latest'
    pullPolicy: Always

podSecurityContext:
  {}